# Would be production compose file
services:
  pong:
    container_name: pong
    build: .
    working_dir: /pong
    volumes:
      - .:/pong
    command: tail -f /dev/null
    ports:
      - "8080:8080"
      - "4000:4000"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
    