services:
  pong:
    container_name: pong
    build: .
    working_dir: /pong
    volumes:
      - .:/pong
    command: tail -f /dev/null
    networks:
      - mynet
  caddy:
    container_name: caddy
    image: caddy:latest
    env_file:
      - ./apps/frontend/.env
    ports:
      - "9000:443"
    volumes:
      - ./infra/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
volumes:
  caddy_data:
  caddy_config:
